### ISSUE TITLE
Migrate Attachments

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/juliaraab.de#7]
### Tasks
- [ ] Prepare identical image sizes
- [ ] Handle and/or redirect media.juliaraab.de 2 juliaraab.de/_media/
- [ ] Network media library
